name: cos30049_ml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pip:
      - joblib
      - wordcloud
